### ISSUE TITLE
Start a journey

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/streamfarer#3]
Let admins start a new journey.

## Draft

API:

```python
L_co = TypeVar('L_co', covariant=True, bound='Stream')

class AuthenticationError(Exception):
    """Raised when authentication to a livestreaming service fails."""

class Channel(BaseModel): # type: ignore[misc]
    """Live stream channel."""

    """URL of the channel."""
    url: str
    """Channel name."""
    name: Text

class Stream:
    """Live stream.

    Any operation may raise an :exc:`AuthenticationError` if authentication fails or an
    :exc:`OSError` if there is a problem communicating with the service.
    """

    """Related channel."""
    channel: Channel

    async def stop(self) -> None:
        """Stop the broadcast of the stream.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

    # Future reference

    class Event(BaseModel): # type: ignore[misc]
        """Live stream event."""

    class RaidEvent(Event): # type: ignore[misc]
        """Dispatched when the channel raids another."""

        """URL of the target channel."""
        target_url: str

    def __aiter__(self) -> Self: ...

    async def __anext__(self) -> Event:
        raise NotImplementedError()

    async def aclose(self) -> None:
        """Close the stream."""
        raise NotImplementedError()

    async def raid(self, target_url: str) -> None:
        """Raid the channel at the given *target_url*.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

class Service(Generic[L_co]):
    """...

    Any operation may raise an :exc:`AuthenticationError` if authentication fails or an
    :exc:`OSError` if there is a problem communicating with the service.
    """

    async def stream(self, channel_url: str) -> L_co:
        """Open the live stream at the given *channel_url*."""
        raise NotImplementedError()

    async def get_channels(self) -> list[Channel]:
        """Get all live stream channels.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

    async def create_channel(self, name: Text) -> Channel:
        """Create a live stream channel with the given *name*.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

    async def delete_channel(self, channel_url: str) -> None:
        """Delete the live stream channel at the given *channel_url*.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

    async def play(self, channel_url: str) -> L_co:
        """Broadcast a live stream at the given *channel_url*.

        If the service does not support the utility, a :exc:`RuntimeError` is raised.
        """

class OngoingJourneyError(Exception):
    """Raised when an action cannot be performed due to an ongoing journey."""

class Stay(BaseModel): # type: ignore[misc]
    """Stay at a live stream on a journey."""

    """Unique stay ID."""
    id: str
    """Related journey ID."""
    journey_id: str
    """Live stream channel."""
    channel: Channel
    """Time the stay started."""
    start_time: datetime
    """Time the stay ended. `None` if the stay is ongoing."""
    end_time: datetime | None

    def get_journey(self) -> Journey:
        """Get the related journey."""

class Journey(BaseModel): # type: ignore[misc]
    """Journey through live streams."""

    """Unique journey ID."""
    id: str
    """Journey title."""
    title: str
    """Time the journey started."""
    start_time: datetime
    """Time the journey ended. `None` if the journey is ongoing."""
    end_time: datetime | None
    """Whether the journey is deleted."""
    deleted: bool

    def get_stays(self) -> list[Stay]:
        """Get all stays on the journey, latest first."""

    def edit(self, title: Text) -> Journey:
        """Edit the journey *title*."""

    def end(self) -> Journey:
        """End the ongoing journey."""

    def delete(self) -> None:
        """Delete the journey.

        Only ended journeys may be deleted.
        """

    # Future reference

    async def resume(self) -> Journey:
        """Resume the ended journey.

        Only the latest journey may be ongoing.

        If authentication to the livestreaming service fails, an :exc:`AuthenticationError` is
        raised. If there is a problem communicating with the livestreaming service, an
        :exc:`OSError` is raised.
        """

    def restore(self) -> Journey:
        """Restore the deleted journey."""

class Bot:
    def get_journeys(self) -> list[Journey]:
        """Get all journeys, latest first."""

    def get_journey(self, journey_id: str) -> Journey:
        """Get the journey with the given *journey_id*."""

    async def start_journey(self, channel_url: str, title: str) -> Journey:
        """Start a new journey at the given *channel_url*.

        *title* is the journey title. Only one journey may be ongoing.

        If authentication to the livestreaming service fails, an :exc:`AuthenticationError` is
        raised. If there is a problem communicating with the livestreaming service, an
        :exc:`OSError` is raised.
        """

    async def stream(self, channel_url: str) -> Stream:
        """Open the live stream at the given *channel_url*.

        If authentication to the livestreaming service fails, an :exc:`AuthenticationError` is
        raised. If there is a problem communicating with the livestreaming service, an
        :exc:`OSError` is raised.
        """
```

CLI:

```
streamfarer journey
Show all journeys.

streamfarer start CHANNEL_URL TITLE
Start a new journey.

streamfarer edit JOURNEY_ID TITLE
Edit a journey.

streamfarer end
End the ongoing journey.

streamfarer delete JOURNEY_ID
Delete a journey.

# Future reference

streamfarer resume
Resume the latest journey.

streamfarer restore JOURNEY_ID
Restore a deleted journey.
```

UI:

```
Roaming
Streamfarer has been on a journey through Twitch for 1 h 15 min now, since 20 Sep 2024 12:00. /
Streamfarer was on a journey through Twitch for 1 h 37 min, from 20 Sep 2024 12:00 until 13:37.
* Frank
  Since 20 Sep 2024 12:00 for 1 h 15 min /
  From 20 Sep 2024 12:00 until 13:37 for 1 h 37 min
```

## Tasks

* [x] Implement draft
* [x] `Bot.transaction()`: Enable foreign keys
* [x] `Service`: Replace `reset()` with `get_channels()` and `delete_channel()`
* [x] `TestCase`: Provide an online channel
