### ISSUE TITLE
Cope with stream interruptions

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/streamfarer#9]
If the current stream is restarted shortly after it stopped, automatically resume the journey.

Depends on #8.

## Draft

```python
L_co = TypeVar('L_co', bound='Stream', covariant=True)

class Stream:
    ...

class Service(Generic[L_co]):
    async def stream(self, channel_url: str, *, timeout: float | None = None) -> L_co:
        """Open the live stream at the given *channel_url*.

        Optionally, the channel is awaited to come online with a *timeout* in seconds.
        """

    async def open_stream(self, channel_url: str, timeout: float | None) -> L_co:
        """Open the live stream at the given *channel_url*.

        Optionally, the channel is awaited to come online with a *timeout* in seconds.
        """

class Journey:
    async def resume(self, *, timeout: float | None = None) -> Journey:
        """Resume the ended journey.

        Optionally, the current channel is awaited to come online with a *timeout* in seconds.
        """

class Bot:
    async def stream(self, channel_url: str, *, timeout: float | None = None) -> Stream:
        """Open the live stream at the given *channel_url*.

        Optionally, the channel is awaited to come online with a *timeout* in seconds.
        """
```

## Tasks

* [x] Implement draft
* [x] `LocalService`: Use `Future` for timeouts
* [x] `Twitch._notifications()`: Yield `_TwitchNotificationPayload`
* [x] `services`: Move `_read_twitch_message()` to `Twitch`

**Comment by noyainrain** [comment]
Unfortunately, the Twitch mock server can only trigger a play event, but not actually start a stream. This makes the following test fail, but it may still be useful for manual testing:

```python
class Twitch:
    async def play(self, channel_url: str) -> TwitchStream: # type: ignore[return]
        if self.api_url == TwitchAdapter.PRODUCTION_API_URL:
            raise RuntimeError('Unsupported operation')
        user = await self._get_user(channel_url)
        await Twitch.cli('event', 'trigger', '--transport=websocket', f'--to-user={user.id}',
                         'streamup')

class WithServiceTest:
    async def test_stream_future(self: ServiceTestProtocol) -> None:
        task = create_task(self.service.play(self.offline_channel.url))
        try:
            stream = await self.service.stream(self.offline_channel.url, timeout=1)
            self.assertEqual(stream.channel, self.offline_channel)
        finally:
            await task
```
